<?php

namespace RentaBundle\Repository;

/**
 * FormularioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioRepository extends \Doctrine\ORM\EntityRepository
{
}
