<?php

namespace RentaBundle\Repository;

/**
 * FormularioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteresadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function interesadosByProceso ($proceso_id) {
        $em = $this->getEntityManager();
        $db = $em->getConnection();
        $query = "SELECT id from interesado where proceso_id = :proceso_id";
        $stmt = $db->prepare($query);
        $params = [":proceso_id" => $proceso_id];
        
        $stmt->execute($params);
        $po=$stmt->fetchAll();

        return $po;
    }
    
    public function deleteInteresados ($proceso_id)    {
        $em = $this->getEntityManager();
        $db = $em->getConnection();
        $query = "delete from interesado where proceso_id = :proceso_id";
        $stmt = $db->prepare($query);
        $params = [":proceso_id" => $proceso_id];
        $po = $stmt->execute($params);
        
        return $po;
    }
}