services:
        
    renta.proceso:
        class: RentaBundle\Entity\Proceso
        arguments: ["null"]        
        
    renta.extraer:
        class: RentaBundle\Services\ExtraerServ
        arguments: ["@renta.proceso"]
#    renta.example:
#        class: RentaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
